### ISSUE TITLE
how to build weasis with isowriter plugin ?

### ISSUE THREAD

**Issue by mbx2015** [nroduit/weasis-isowriter#1]
Hello, 
How can we build weasis with isowriter plugin ? I can't find anything on how to do so, nothing in the docs.

thanks

**Comment by nroduit** [comment]
To build:

1. Build the portable distribution of Weasis
1. Build isowriter plugin: mvn clean install

Or use directly weasis-ext.war from https://sourceforge.net/projects/dcm4che/files/Weasis/3.0.4/
For the portable version, see https://nroduit.github.io/en/faq/ ( Can Weasis be incorporated in DICOM CDs or other removable media?)
